
import Link from "next/link";
import { Download } from "lucide-react";
import { buildSeo } from "@/lib/seo";
import type { Metadata } from 'next';

export const dynamic = 'force-dynamic';

export async function generateMetadata(): Promise<Metadata> {
  return await buildSeo({
    title: 'CMS JSON Snapshots',
    description: 'Download 1:1 snapshots of live Firestore CMS documents.',
    noIndex: true,
  });
}

const SNAPSHOTS: Array<{
  slug: string;
  label: string;
  filename: string;
  description?: string;
}> = [
  {
    slug: "site-settings",
    label: "Site — Settings",
    filename: "site-settings.json",
    description: "Global site/SEO settings from site/settings.",
  },
  {
    slug: "site-navigation",
    label: "Site — Navigation",
    filename: "site-navigation.json",
    description: "Main navigation document used for header and footer.",
  },
  {
    slug: "pages-home",
    label: "Page — Home",
    filename: "pages-home.json",
    description: "Homepage document from the pages collection.",
  },
  // Add more entries for other snapshots if they exist in DOCS/snapshots
];

export default function CmsSnapshotsPage() {
  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">
          CMS JSON Snapshots
        </h1>
        <p className="text-sm text-muted-foreground mt-1 max-w-2xl">
          Download the current Firestore CMS documents as JSON snapshots. 
          These files are generated by the `export:cms-snapshots` script and reflect the live data structure.
        </p>
      </header>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {SNAPSHOTS.map((snapshot) => (
          <div
            key={snapshot.slug}
            className="rounded-xl border bg-card p-4 shadow-sm flex flex-col justify-between"
          >
            <div>
              <h2 className="text-sm font-medium">{snapshot.label}</h2>
              <p className="text-xs text-muted-foreground mt-1">
                {snapshot.description}
              </p>
              <p className="text-[11px] text-muted-foreground mt-2">
                File: <code>{snapshot.filename}</code>
              </p>
            </div>
            <div className="mt-4">
              <Link
                href={`/api/dev/cms-snapshots/${snapshot.slug}`}
                className="inline-flex items-center rounded-md border px-3 py-1.5 text-xs font-medium hover:bg-accent"
              >
                <Download className="h-3 w-3 mr-2" />
                Download JSON
              </Link>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
